rvm:
  - 1.8.7-p352
  - ree-1.8.7-2011.03
  - 1.9.3-p0

notifications:
  recipients:
    - support@typuscmf.com

branches:
  only:
    - master
    - 3-1-stable

before_script:
  - "psql -c 'create database typus_test;' -U postgres >/dev/null"
